version: "3.9"
services:
  api:
    build: .
    container_name: ai_api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis
      - ollama
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A app.services.celery_tasks worker --loglevel=info
    depends_on:
      - redis

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

volumes:
  ollama_models:
